name: offbeat_pravasi_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  http: ^1.3.0
  go_router: ^14.6.2
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  flutter_phoenix: ^1.1.1
  appwrite: ^15.0.0
  image_picker: ^1.1.2
  lucide_icons_flutter: ^2.0.0
  percent_indicator: ^4.2.4
  google_nav_bar: ^5.0.7
  flutter_rating_bar: ^4.0.1
  flutter_image_slideshow: ^0.1.6
  flutter_markdown: ^0.7.6+2
  flutter_card_swiper: ^7.0.2
  flutter_slidable: ^4.0.0
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.4
  dropdown_textfield: ^1.2.0
  camera: ^0.11.1
  flutter_image_compress: ^2.0.4
  path_provider: ^2.1.5
  path: ^1.9.0
  intl: ^0.20.2
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.4
  story_view: ^0.16.5
  flutter_local_notifications: ^19.0.0
  direct_call_plus: ^1.0.4
  permission_handler: ^11.4.0
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
