name: offbeat_pravasi_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  http: ^1.2.2
  go_router: ^14.6.2
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  flutter_phoenix: ^1.1.1
  appwrite: ^14.0.0
  image_picker: ^1.1.2
  lucide_icons_flutter: ^1.2.7
  percent_indicator: ^4.2.4
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
