name: Flutter Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Install dependencies
        run: flutter pub get

      - name: Build app with secrets
        run: |
          flutter build apk \
            --dart-define=APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }} \
            --dart-define=APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }} \
            --dart-define=APPWRITE_USERSTORAGE_BUCKET=${{ secrets.APPWRITE_USERSTORAGE_BUCKET }} \
            --dart-define=APPWRITE_TREKIMAGE_BUCKET=${{ secrets.APPWRITE_TREKIMAGE_BUCKET }} \
            --dart-define=APPWRITE_USERBANNER_BUCKET=${{ secrets.APPWRITE_USERBANNER_BUCKET }} \
            --dart-define=APPWRITE_USERPOSTS_BUCKET=${{ secrets.APPWRITE_USERPOSTS_BUCKET }} \
            --dart-define=APPWRITE_NOTIFICATION_ENDPOINT=${{ secrets.APPWRITE_NOTIFICATION_ENDPOINT }} \
            --dart-define=APPWRITE_USERSTORY_BUCKET=${{ secrets.APPWRITE_USERSTORY_BUCKET }} \
            --dart-define=STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
